insert into app_professor(address,name,phone,salary) values("London","Winston Churchill","+4425786512","2000");
insert into app_professor(address,name,phone,salary) values("London","Stephen Hawking","+4437216498","2000");
insert into app_student(address,email,marksaverage,marksbook,name,phone) values("34 Ridgmount Gardens, London, UK","bob.marley@gmail.com","0","1212123434","Bob Marley","+4412312312");
insert into app_student(address,email,marksaverage,marksbook,name,phone) values("4 Central Square, London, UK","freddy.mercury@gmail.com","0","1032023421","Freddy Mercury","+4476305634");
insert into app_seminar(professor_id,name,number,fee) values("1","Mathematics","01","100");
insert into app_seminar(professor_id,name,number,fee) values("1","Physics","02","100");
insert into app_seminar(professor_id,name,number,fee) values("2","Social Communications","03","100");
insert into app_progress(seminar_id, student_id) values("1","1");
insert into app_progress(seminar_id, student_id) values("1","2");
insert into app_progress(seminar_id, student_id) values("2","1");
insert into app_progress(seminar_id, student_id) values("2","2");
insert into app_progress(seminar_id, student_id) values("3","1");
insert into app_progress(seminar_id, student_id) values("3","2");
insert into progress_marks(progress_id, marks) values("1","4");
insert into progress_marks(progress_id, marks) values("1","4");
insert into progress_marks(progress_id, marks) values("1","3");
insert into progress_marks(progress_id, marks) values("2","5");
insert into progress_marks(progress_id, marks) values("2","4");
insert into progress_marks(progress_id, marks) values("2","3");
insert into progress_marks(progress_id, marks) values("3","4");
insert into progress_marks(progress_id, marks) values("3","3");
insert into progress_marks(progress_id, marks) values("3","4");
insert into progress_marks(progress_id, marks) values("4","4");
insert into progress_marks(progress_id, marks) values("4","5");
insert into progress_marks(progress_id, marks) values("4","3");
insert into progress_marks(progress_id, marks) values("5","3");
insert into progress_marks(progress_id, marks) values("5","4");
insert into progress_marks(progress_id, marks) values("5","3");
insert into progress_marks(progress_id, marks) values("6","4");
insert into progress_marks(progress_id, marks) values("6","4");
insert into progress_marks(progress_id, marks) values("6","3");